# Generated by Django 3.1.2 on 2021-05-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0018_remove_workshop_noofevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=150)),
                ('Password', models.CharField(max_length=150)),
                ('Username', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
        migrations.AlterField(
            model_name='feed',
            name='Video',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
