# Generated by Django 3.1.2 on 2021-05-27 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0019_auto_20210526_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='Session',
            new_name='Duration',
        ),
    ]
