# Generated by Django 3.1.2 on 2021-05-27 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0020_auto_20210527_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Session',
            new_name='Duration',
        ),
    ]
