# Generated by Django 3.1.2 on 2021-05-29 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0021_auto_20210527_2129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Staff',
        ),
        migrations.AlterModelTable(
            name='staff',
            table='Staff',
        ),
    ]
