# Generated by Django 3.1.2 on 2021-05-31 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0023_auto_20210530_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ProgrammeName',
            field=models.CharField(max_length=150),
        ),
    ]
