# Generated by Django 3.1.2 on 2021-06-01 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0025_auto_20210601_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='Graph',
        ),
    ]
